apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-12-27T03:31:38Z"
  name: pod-reader
  namespace: default
  resourceVersion: "864"
  uid: 6cdb68dd-63c8-49ec-943f-22f807558f94
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2023-12-27T03:31:38Z"
  name: read-pods
  namespace: default
  resourceVersion: "865"
  uid: 494d1916-7ae7-4d50-a825-7317c74d41e4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: dashboard-sa
  namespace: default

